language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "harupong(via TravisCI)"
- git config --global user.email "harupong@gmail.com"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..23}" ]; then echo 'No $id_rsa_{1..23} found !' ; exit 1; fi
- echo -n $id_rsa_{1..23} >> ~/.ssh/travis_rsa_64
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- bundle exec rake setup_github_pages[$REPO]
- git checkout -- _config.yml
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - REPO="git@github.com:harupong-blog/harupong-blog.github.io"
  - secure: f/PFDWO1yTXChucoBw2yino3NtGX1HCEkk5vYMQJ0qGp9lX+IDGwgYvqO9gEf/+qLoZEtwOgtH6PvjSy+rpyfgMDNJmSd4IjGReo5bxI8t9vh7Hwgx4RdU7uzJF4xrL1nXUrKnkUmaEz4I0UZL26xISL3HcV9CW4b7HPf2TuHzg=
  - secure: ho6KMSxhrBQ1q8YnhcG/4/VLZ/+p+4bykDEtG2DFrZWfuwYmZhTwyJUNzmVADQHKeW1SRPkAvZSCXb5Xvg9B655zwnd8hRdZStrTvfUrCCdmLmlMR8BxNb4Ipg2VLUTMB/rUVY8lXg2ZIQlZDa4r0k2crmQyqr5g7JUuD3+vb+4=
  - secure: tS95CfCBfhbMuxBB2CWRFL3gDAKcEWNRc2e7v7J5Wh2gC4vs3iyx0JEKaKdDPhr1aKH1WQeRs0LdyuOSK2ykYqI4lhR4+ZnI+J4rwXAhLnRXL+MHvcnI0AnbI042PeyqG0k6Ysj9kp6o9f0Q9Jn0YSvj0oVKfqeaON2sRvprgoE=
  - secure: Sm7SwK6ly34AsrpBUiiw0JAKjlUkIb7iTJ27b56egYJKPmJc/wUgAPtJsk1eEgckjMSHqDKX3uTssX4jw9GCCVPGvy4UobBj03yNbif2thTZnxnrwcfBuKsDBk/chDa6/VwrfGCyAzoqzsFtp66gEXOgZ3sZcAcBzBVksIJgGOw=
  - secure: cqSDQMyunavBMnfCCeymoPDFeETkLPQEeqapAGDyIX+uRMJpqexGbXZXCH4/zbYHIw9k3br/trdXwsbsMbdKvLziyhe4BrAIZM+k0i0eK0Zo5t0bmFYhSdm+lFEj+tlCsPZCMI2q11g6jKqXQy/mPEkJH2TkaE5trI3OMhK3Ntw=
  - secure: GkxoOcGNaYpURTh68Kj2Hl1Q/1hlQgb8l7y1jt6i3nwK7EPXEOfs5brS+Gq6DxpQP4BqRqtfgb/zzjYd5RUT9+WQ+LJD9sT3ydM4Fi1IuEMSezJeLA0waJnZSmVagz+I525HIjS82Lp+bOUk4T/FYJ2Qeq0C+uRFmvXKZvLMUck=
  - secure: Vdw4BUryGub0Ks1esuor8V1+5qeN1cT7kPyJ2XJBXeabKqulVkSS4wgrIlJJ4J+YtJec1cPpMuH2buGruyQwgK8G+a8Tw85A2uknK1/LCotVJrzWZ0PchAowV6Jw/+Gu+0osSP0YaqtJ4DKoFrKfjTtRsAG8drjoz1z8xw2aHW8=
  - secure: S0hprwjWlWxj9JdYn1pDVDTW/l6CGuVDsYTwHRjWEvjDYNnkv06IR+BXW40LErewGo2bFO9jt+DeEJmTaJz8bGg2AzMbAD5xpD1K2jesmerp/JrBaGHpk5K3aEclruBCIrFu0Hgje6sM6l40rDBX7GcKI5pLZVEMl9LGhy50RyM=
  - secure: Jjb+2Cjc2Iphf1nATeEOHQECduPKdn59AKUutaP1tjpehojz3DdYnjHhNOX2R9WEZ2q2PsvQqwx7nFy1eQY4ftotZUt2jZ2Rc6MLR7TxlUn4fAsTWiUpPqHgAXm8VK996E9lUuU/Q1Qe7DkU2jupTeyL+cObBpvLzKYV7X91xLc=
  - secure: eNiK8gq1fpcN9x6R4KVLd33KjsrAbNxTR0CabU2O4nlS37lr2foPX9vQM+xpdLDrbF3KkRvZ5QDSTdIRKA3+uJtxJWx59XcwOpURP7zuS32ep/Syw/vCsSJZjEo0a0dtGJsNTHhT2Lt1FXuRTKLPPZXD5tyPvUt52HScfOmut7s=
  - secure: moudV8Gul80bgbq/3s3zcGOwa6sxBKkZz+BBOYQwk09nxTu9xrkC627h8Cm6v/ClWOKuGbklyecI3fq543PQ40n1hvRfPVt9nECQqlRtUOqAPM/Vd9XOYC9LBr7JIEFZDGb4ibBDsnKIT+3gahbL37HW1ehwqCG02jcjRdOKbrA=
  - secure: pvO587h11+X/4+mojsaiqu7eOLnGPtUQrwOAwR1oj9XgW5i1CP7uEKI2WwzMjB4YNmXnigtVUEj9pSa9vHKWYopbwhNfRpnr3o2Hp3I34DHZlVyn+pvicDIxOEpTbaTG83j4w5FqNYN94wBoxkW6iDlfU3T9VwbPIRYzXv8ULW0=
  - secure: ViTnVN/pNuHhlKC0t1vZPpulhPnapwn1wRqylrcIoJYjYeKvWinXnc4VIa91WY5eL9N+z7LXASoJ9TQ7WdmKWy/WyaIOSir+kkBRjha8Qpkt92DLnPN//f5uYproe5rodPAAC7IE5HU9K/I3pTKQSsMpho+ygN5NkIAdzQYzj3M=
  - secure: Gw7rG8v3RQ4V5LXeeMvx31gNEcVzpVlapRAw9bQ1YGaATwNBjaBgixtErCxiUj9U9l51lsQq8L1cdMPABYJFtL11PHa+PBoN0SpKNc7Zdt59LixKuLeahUII7MR3wN/ucYsLGx5yrZLQ4VFeEky+BXnZnSvyzmZtpWMbLHZSpRY=
  - secure: kyM+pb8yDpZeFPXvSd15OG9x3w9NHVXVu7QQes0S1Snqo4S5t8DpkjNn0khUcEINdli9EM8Y3GUesJZMBmisDmV4eOlrY9HCy1lUPRXCufoGG1pV/jHmyKSFc82spzcq8NVS6Y9NxjUy6vfUGLQocp/rf99SnHs+cV/m9iFHdDU=
  - secure: W7eSWtFVtppbPnz2C17QIRTLTXASKzkx/uKxgXu/AC5dYZy5wuWEXWAeCbPVvsIigDbEJfEa6bSwCmmLbYhEwp5awWQ7BzlzrcJcq6U5sMN6TELAprg/chb3o/Ez/UniK89VgRNMzvZBY/CI5LkpeCFO0awuFp4k8D82CFCqC8s=
  - secure: B5UKiAhKJjmSd+qQhAqUzjOe345Tf1amtPSHPJg3jusWap68YZtq7F5fyakiUir67Q24Oc8P6JNtizsArEIsaCI82ltGNWVOMRXc6eM5Jzf+9QYb6For8eZF/WHHDkBUGFWa8Gv30I9pQ0UHJh9IQR9IGeAYzX4/zwOQSEB3Skg=
  - secure: uqWwTTDqJB5jpYxnPVMR26rI3Ufi6oU++dNQoPMCKTGFKyG8Hve9WTlMomgLg/9D9MZ70hQxsQr95V8ybszo4D7TIXeHQYw26YuGCnz4XcXOOwTiVq4dmMeI1MLFoM4PHJ2ck2nS+6/I0HM37XI4QUmAf2uE5pYmqjG1Lc70MT8=
  - secure: kMpfniNEvRB0PkdNuGnLdY/H6y3mAskTWRhgkWQqZo1j8UmATTwfjCQpd7tyiiFb1hL+/5KxLuMWIpyttkpNM2oetMMek+Dks1G8LTk5Lx8V78njKqIq0D9XDQU8IAo/jzf17YGKHe2VAYcxtn9PF7J2V/2q/K0uZYi9GbuwjTY=
  - secure: NBiptF3Rq/EeomrBjGAi33SueUd4eXSW2E9TX6No8JqC3HhHCqQv7GPj4EUA3PPJ5rQxT7brUPHrsGgI1h9n7OQy5M9STes4pfoXGnBOBiIK0oOPpj60psmLkwzFoHgAWqbC3blKKnx3kswDucVFBkekz7sIVQqnNToUWVNeqGc=
  - secure: ntCoU4k/2nwww5QeNokf7ArZ/GEKTXQh8RO+Z+YCk1p9GO8sYnoA2yJ293E5MDTNn3w55WmS5rBjKORcPppX2m1c83D2InqffOc2jLbSGzBUivALcA6yHWL998+4Bny5ucDAHC9voOoRntqvg0W++N7YXbnKmZtZET3lp2/hSEA=
  - secure: Yn/0/O8eR6HW0+qMUuT1D7eCnXLggI4+Pn9qrVu9ZrnjrKgYYnCvi6/9IUf3dish7nEtxdrcU3QTl8HYdCTXu5S7PQteJoduDvRMiELrLtuypPIXhtbi8jY2jDZuZHVlEYrwMAkmudJW19Mni9V1X2tFO1O6bjJNHfh9CoMvoTI=
  - secure: E2b9HIqT0pjRFept+x8UqFim80UffDHiEk9+hZeeY5uaiLogf8Zx6skPg71rtO5e3AmHH5LhsKBfG823kKsYqbn8jqpSPYir1ZiuYAdk0nqx87yeU0nMT4AIMBAz11cnjSg0hv93O3aEv3Frv4nvifsc/JDU//sOkm9hTUO16kE=
  - secure: CR6M1Wsia+wDKGeu1T2dl2WycxymY8GCvwuxqqsuctrjC/YZ3pkPWbECcv1wECbvBR9ZNj22bJLleRpseA4Efvnw/X8XMuUKPWCOA6aKKBkGO2ha6UNpn+na9c5XDKCLvWNFvzy8vyVpRyXNJI5+T2kXb4+0m2+R/+zU1KrfKP4=
  - secure: LlTwwKTKL2zV4vdUUgckDqQaBpbyZAmXJgJ6x34FIUZ2/GYju8r/63/LHFt8ov3Ci5NOBblQm/2I/WTW4uUkn2W2lu21Ny+RzoUChZ5KGmCpkRJy2GeQkywzUfkoUGWqZBNr3Dka5z6UdN//GG+8XVMM6db8Ap/QdfCT/nhEwms=
  - secure: h325a3vcRu6oH3ayaK90j0MBk80ufDTXDFY69VQuWXkEucPS9TtUW8nC+U8SNtXx7GUC9eJZSsBfqbcimKem5S0txVMPff6chOm5xeDOO/VEWFXO50dzETuTi/CCXxjSURFIF+wxJa7YdjPm7Lck9xwJGYemEJGPbA4C81Q3GUU=
  - secure: i/VFkg+Gnt9F+A89cFZqNH2fr2Y5klIrodoY+lWA6YvYqnBbKm+zQR96Ax9uNdFX2t4+kQuBi5d1GN4XqE+XiTOBwnOAoS6RDWV7UjCNDx037Zu2iDV7W9K6lI1MDkuY2uwNqvEzk5/7lCvQyi1DGjAuhHETTd6h2+xl7lImfB4=
  - secure: ONUSZpiu3Hu1Ke4UHjsBRUCFJ++nZDWN48ByV7J7ngXZfqWnOqlNdghUOrgVZWpZFNfg/G/uMhgcstBHzVItfgSbDblvaXReViMd4w8ms8q7x5/8ub2Gc6TtwCOwpyLDLWlscWh0/ZgTJewakm65F671eQi4mU6zz0K+3jnFr0Y=
